const laptop = [{
	id:11,
	title:"Acer Aspire 7 Core i5 9th Gen",
	description:"Become more productive with the Aspire 7 laptop from Acer. With the 9th Gen Intel Core™ CPU, 32 GB of DDR4 SO-DIMM RAM and 1 TB M.2 PCIe SSD capacity, this laptop delivers a power-packed performance. Transfer data at a rapid speed, thanks to the 4 ports that this laptop offers. Moreover, immerse yourself in captivating visuals with the Acer Colour Intelligence and Acer ExaColor feature that enhances your visual senses.",
	price:10,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/laptop/acer.jpeg",
},
{
	id:12,
	title:"Asus VivoBook 14 Ryzen 5 Quad Core 2nd Gen",
	description:"Enjoy a hassle-free computing experience when you have the ASUS VivoBook 14 laptop. It features the trendy NanoEdge Display, the ErgoLift hinge, and a full-size backlit keyboard for effortless computing. Oh, and not to forget, it features the ASUS SonicMaster technology for an enthralling aural experience.",
	price:20,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/laptop/asus.jpeg",
},
{
	id:13,
	title:"HP Pavilion Gaming Ryzen 5 Quad Core",
	description:"If you’re looking for a sleek yet powerful laptop that is perfect for, both, work and play, then you must buy the HP Pavilion Gaming 15 Laptop. Whether it's playing games or multitasking between applications, this laptop offers a smooth and lag-free performance as it features an AMD Ryzen 5-3550H processor and 8 GB of DDR4 RAM. Enjoy an immersive viewing experience, thanks to the 39.62-cm (15.6) Full HD display and dual speakers as well as B&O Audio.",
	price:30,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/laptop/hp.jpeg",
},
{
	id:14,
	title:"Dell Vostro Core i3 10th Gen",
	description:"Bring home the Dell Vostro and enjoy the smooth multitasking and the computing power of its 10th Gen Intel Core processor. Store all of your files in its 1 TB HDD that provides ample space for all your favourite games, music and movies, among other things. The Trusted Platform Model 2.0 featured in this laptop ensures that all your data remains secure even if the hard drive were to be stolen and installed in another computer.",
	price:40,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/laptop/dell.jpeg",
},
{
	id:15,
	title:"Lenovo Ideapad 3 Core i5 10th Gen",
	description:"Pre-installed Genuine Windows 10 OS.Preloaded MS Office Home and Student 2016.Light Laptop without Optical Disk Drive.15.6 inch Full HD LED Backlit Anti-glare TN Display (220 nits Brightness, 16:9 Aspect Ratio)",
	price:50,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/laptop/lenovo.jpeg",
},
{
	id:16,
	title:"Acer Aspire 5 Core i5 10th Gen",
	description:"Stylish & Portable Thin and Light Laptop. 14 inch Full HD LED Backlit IPS ComfyView Display (16:9 Aspect Ratio).Light Laptop without Optical Disk Drive",
	price:25,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/laptop/acer.jpeg",
},
{
	id:17,
	title:"Asus VivoBook 14 Core i5 10th Gen",
	description:"You can use this 35.56 cm (14) Asus VivoBook for work-related purposes or or entertainment purposes. It comes with a powerful battery, so you can use it for work while travelling, or you can use it to play games for hours on end. You can even carry it with ease, as it has a compact structure. What’s more, it comes with a Fingerprint Sensor and Windows Hello. These features ensure easy access to the contents of your laptop and also remove the trouble of having to remember passwords.",
	price:65,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/laptop/acer_gaming.jpeg",
},
{
	id:18,
	title:"HP Omen Ryzen 5 Hexa Core",
	description:"With a powerful AMD Ryzen processor and NVIDIA graphics in a compact frame, this gaming laptop from HP is the one for any gamer. Apart from featuring a fast display and a long battery life, it also comes with the OMEN Command Center, and graphics cooled by OMEN Tempest Cooling, making this laptop a perfect example of how there can never be too much of a good thing.",
	price:70,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/laptop/hp_gaming.jpeg",
}]

export default laptop