const phone = [{
	id:1,
	title:"Tecno Camon 15 (purple 64 GB)(4 GB RAM)",
	description:"This Tecno Camon mobile phone is here to keep you hooked to its innovative features and stylish design. It features a big 16.64 cm (6.55) HD+ Dot-in Display that will give you an immersive experience, every time. The 5000 mAh Large Battery will give you enough power to game, stream content, listen to music, and more without constantly running to the nearest charging station to power up your phone.",
	price:15,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/phone/tecno_camon.jpeg",
},
{
	id:2,
	title:"Vivo V17 (Midnight Black, 128 GB)  (8 GB RAM)",
	description:"Stunning pictures, enough space to store everything, and seamless performance - everything is possible with the Vivo V17 smartphone. It comes with features such as the Super Night mode, a quad-camera system (48 MP main camera + 8 MP super wide-angle camera + 2 MP macro camera + 2 MP bokeh camera), and a 32 MP front camera to help you capture gorgeous pictures. With the presence of a 4500 mAh battery, you can count on this phone to be by your side for work and leisure.",
	price:20,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/phone/vivo17.jpeg",
},
{
	id:3,
	title:"Realme 5 Pro (Chroma White, 128 GB)  (8 GB RAM)",
	description:"8 GB RAM | 128 GB ROM | Expandable Upto 256 GB.16.0 cm (6.3 inch) Full HD+ Display,48MP + 8MP + 2MP + 2MP Quad Camera | 16MP Front Camera | 4035 mAh Battery | Qualcomm Snapdragon SDM712 Octa Core 2.3 GHz Processor | VOOC Flash Charge 3.0 | Triple Card Slot",
	price:25,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/phone/realme_5_pro.jpeg",
},
{
	id:4,
	title:"Mi A3 (More Than White, 128 GB)  (6 GB RAM)",
	description:"Boasting a reflective coating and a nano-level holographic pattern, this smartphone from Mi looks jawdropping. It also features a Qualcomm Snapdragon 665 AIE processor that packs a punch when it comes to smartphone performance. And, if you’re an entertainment enthusiast, then you can take advantage of its 15.4-centimetre (6.08) Super AMOLED display to watch your favourite videos in high definition.",
	price:50,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/phone/redmi_a3.jpeg",
},
{
	id:5,
	title:"Honor 9x Pro (Phantom Purple, 256 GB)  (6 GB RAM)",
	description:"This stylish Honor Mobile Phone is here to make an impression with not just its looks but also with its innovative features. Its FullView Display gives you an immersive experience while streaming movies or gaming. Thanks to its Blue Light Filter, your eyes will be protected from excessive fatigue. With a 48 MP (main camera) camera, 8 MP (super-wide-angle camera), and a 2 MP (depth-assist camera), you can enjoy taking stunning pictures with the Triple Camera setup of this mobile phone.",
	price:60,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/phone/honor_9x_pro.jpeg",
},
{
	id:6,
	title:"Honor 20 (Sapphire Blue, 128 GB)  (6 GB RAM)",
	description:"Capture stunning images, wherever you go, with the HONOR 20 smartphone. Its four rear cameras (16 MP + 48 MP + 2 MP + 2 MP Macro) let you capture beautiful landscape images, eye-catching close-up shots, and bright images even under low-light conditions. Oh, and when you want to click a selfie, you can do so, with this smartphone’s 32 MP high-resolution front camera. This smartphone is powered by the Kirin 980 chipset and the GPU Turbo 3.0, thereby facilitating a lag-free performance, even while gaming.",
	price:70,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/phone/honor6.jpeg",
},
{
	id:7,
	title:"OPPO A9 2020 (Space Purple, 128 GB)  (4 GB RAM)",
	description:"Surprise yourself every day with your ideas and capabilities with the Oppo A9 2020. This phone comes with a 48 MP rear camera with an ultra wide 119° rear lens to help you click amazing pictures with extra dimension and depth and a 16 MP front camera with AI Beautification to let you click picture-perfect selfies. You can immerse yourself in crystal-clear, thanks to the dual stereo speakers and Dolby Atmos that come with Widevine L1 Certification.",
	price:80,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/phone/oppo_a9.jpeg",
},
{
	id:8,
	title:"POCO F1 (Steel Blue, 256 GB)  (8 GB RAM)",
	description:"Meet the POCO F1 - the first flagship smartphone from POCO by Xiaomi. The POCO F1 sports Qualcomm flagship Snapdragon 845 processor, an octa-core CPU with a maximum clock speed of 2.8 GHz which is supported by 8 GB of LPDDR4X RAM. It is coupled with a LiquidCool Technology that allows the device to sustain peak performance for a longer period of time. On the back, it features a 12MP + 5MP Dual Pixel AI dual camera setup. The main camera sensor features 1.4 um pixels, Dual Pixel Autofocus, and Multi-frame noise reduction. On the front, it sports a 20 MP high-res front camera and IR Face unlock. POCO F1 also boasts of a massive 4000 mAh (typ) battery with Quick Charge 3.0 to keep you going all-day long.",
	price:100,
	cart:false,
	total:0,
	subtotal:0,
	tax:0,
	image:"work/phone/poco.jpeg",
}]

export default phone