const tv = [{
	id:21,
	title:"Mi 4A PRO 80 cm (32) HD Ready LED Smart Android TV With Google Data Saver",
	subtitle:'Mi 4A PRO',
	description:"There is no fun in watching your favourite movie or show on a TV where the display quality is poor. Now, boost the fun and watch them all in good and clear-quality on this 80 cm (32) Mi smart TV. Its HD Ready display can accentuate your viewing experience and make it better. You can even access video streaming apps on it and never run out of quality-content to watch and enjoy. It comes with 2 speakers that deliver powerful audio which lets you experience the environment of a cinema hall right in your bedroom or living room.",
	price:10000,
	cart:false,
	total:0,
	count:0,
	image:"work/tv/mi.jpeg",
},
{
	id:22,
	title:"Realme 80cm (32 inch) HD Ready LED Smart Android TV  (TV 32)",
	subtitle:'Realme Smart Android TV',
	description:"Bring home this TV from realme and experience the stunning visuals that result from its Chroma Boost Picture Engine. Boasting a Bezel-less design and Dolby Surround Audio, this Android TV blends right into your decor and offers you audio performance that makes your favourite TV shows, movies, and other video content all the more enjoyable.",
	price:30000,
	cart:false,
	total:0,
	count:0,
	image:"work/tv/realme.jpeg",
},
{
	id:23,
	title:"Samsung 80cm (32 inch) HD Ready LED Smart TV with Voice Search",
	subtitle:'Samsung smart Tv',
	description:"Take entertainment to the next level with this smart TV from Samsung. These TVs are not just built to redefine entertainment, but also add a touch of style to your home’s interiors as well. Dive into the cinematic world with cutting-edge technologies like HDR and PurColor that enhance your viewing experience like no other. What’s more? You can transform this TV into a virtual music system that comes in 3 different colour tones. Moreover, the One Remote makes life easy by just having to use that to change tracks, channels and control volumes.",
	price:25000,
	cart:false,
	total:0,
	count:0,
	image:"work/tv/samsung.jpeg",
},
{
	id:24,
	title:"Vu Premium 108cm (43 inch) Full HD LED Smart Android TV",
	subtitle:'Vu Premium SmartTv',
	description:"Delight your senses by watching your favorite shows on this Vu smart Android TV. With its A+ grade panel, seven picture modes, Adaptive Luma Control feature and 24 W speakers, this TV ensures an immersive audio-visual experience. It also allows you to access various content from different streaming services, including Netflix, YouTube, and Hotstar",
	price:35000,
	cart:false,
	total:0,
	count:0,
	image:"work/tv/vu.jpeg",
},
{
	id:25,
	title:"iFFALCON by TCL 79.97cm (32 inch) HD Ready LED ",
	subtitle:'IFFALCON SmartTv',
	description:"Bring home this 81.28-cm (32 inches) TV from iFFALCON and enjoy your favourite video content in HD Ready Resolution. Packed with amazing smart features such as Google Voice Search, Google App Store and Built-in Chromecast, this TV makes accessing entertainment convenient for you, so you can enjoy leading the amazing life of a couch potato.",
	price:30000,
	cart:false,
	total:0,
	count:0,
	image:"work/tv/iffalcon.jpeg",
},
{
	id:26,
	title:"LG All-in-One 80cm (32 inch) HD Ready LED Smart TV",
	subtitle:'LG SmartTv',
	description:"Are you tired of accessing your entertainment on small screens? Bring home this 80 cm (32) HD Ready LED Smart TV. This is the 2019 Edition that boasts Active HDR that is combined with a Quad-core Processor to deliver sharp, upscaled images. All your content will now look lifelike. The DTS Virtual X and Dolby Audio deliver a listening experience that will leave you enthralled.",
	price:45000,
	cart:false,
	total:0,
	count:0,
	image:"work/tv/lg.jpeg",
},
{
	id:27,
	title:"Motorola 109cm (43 inch) Ultra HD (4K) LED",
	subtitle:'Motorola SmartTv',
	description:"Whether you're watching a movie, your favourite TV show, or playing a game on a console with your friends, this Ultra HD (4K) LED Smart Android TV from Motorola is here to transform your entertainment experience. While features such as AutoTuneX Display Technology and Dolby Vision + HDR 10 provide stunning visual quality, the AmphiSoundX feature provides an amazing sound experience. Also, with this TV's remote that comes with Hotkeys and Google Assistant, finding and navigating content is a piece of cake.",
	price:20000,
	cart:false,
	total:0,
	count:0,
	image:"work/tv/motorola.jpeg",
},
{
	id:28,
	title:"Nokia 139cm (55 inch) Ultra HD (4K) LED Smart Android TV",
	subtitle:'Nokia SmartTv',
	description:"Bring home this Nokia Smart TV and transform your entertainment experience. With features such as Intelligent Dimming, DTS Trusurround, and Dolby Audio, get ready for a truly cinematic experience. What's more? With Google Assistant's voice command interface, finding your favourite TV shows and movies is a piece of cake.",
	price:15000,
	cart:false,
	total:0,
	count:0,
	image:"work/tv/nokia.jpeg",
}]

export default tv